### ISSUE TITLE
[Question] 테스트 혹은 Class 작성마다 하는 @Autowired에 대한 질문

### ISSUE THREAD

**Issue by JisuPark-dev** [Keep-Going-Web-Study/BE-Spring-Test-Guide#10]
### 질문1) 왜 @AutoWired를 사용하는가? import해서 해당 클래스를 가져오는 것과 @AutoWird를 사용하는 것은 어떤 차이가 있나요?

import : A객체가 B객체를 참조할 수 있도록 해줌. new 키워드를 사용해서 생성해야함.
@AutoWired : 스프링 컨테이너가 자동으로 필요한 빈을 생성하고 주입합니다. 개발자는 객체 생성과 관리를 신경 쓸 필요가 없습니다.

### 질문2) 빈은 무엇인가요? 빈이라는 것은 왜 사용하나요? 빈을 사용한 코드와 사용하지 않은 코드 예시를 통해서 빈을 왜 사용해야하는지 알려주세요, 그리고 빈으로 의존성 주입한다는 것도 설명해주세요.
- 스프링 컨테이너에 등록된 객체를 스프링 빈이라한다.
- 빈 사용의 가장 큰 이유는 스프링 간 객체가 의존관계를 관리하도록 하는 것에 가장 큰 목적이 있다.  객체가 의존관계를 등록할 때 스프링 컨테이너에서 해당하는 빈을 찾고, 그 빈과 의존성을 만든다. 

- pring Bean을 등록하는 방법은 대표적으로 3가지 정도가 있다.
xml에 직접 등록
@Bean 어노테이션을 이용
@Component, @Controller, @Service, @Repository 어노테이션을 이용

**Comment by JisuPark-dev** [comment]
약간 빈(controller)이 빈(Service)에 의존하면서 되는 그런 구존가 어렴풋이 생각이 되는데...잘 모르겠습니다.

**Comment by JadeKim042386** [comment]
@JisuPark-dev 일전에 강의에 대해 제안 주셨을 때 Spring에 대한 사전 지식이 있으신 줄 알았는데 익숙치 않으신 듯 합니다. Spring에 대해 어느 정도까지 이해하고 계시는지 대략 말씀해주실 수 있을까요? 그래야 어디부터 답해야할지 알 수 있을 것 같습니다.

**Comment by JisuPark-dev** [comment]
@JadeKim042386 거의 아는게 없다고 생각하시면 좋아요

**Comment by JadeKim042386** [comment]
@JisuPark-dev 

우선 Spring의 내용은 방대하기 때문에 처음부터 설명해드리기에는 무리가 있습니다. 그리고 현 스터디의 주제는 테스트 코드를 학습하는 것이기 때문에 Spring에 대한 학습은 개인적으로 진행해주시길 권해드립니다.

1) 스프링에서 빈을 등록하면 스프링 컨테이너에 싱글톤 패턴으로 저장해두고, 다양한 주입 방법으로 스프링이 대신 스프링 컨테이너에 등록한 빈을 가져와줍니다. 이를 IoC라고도 합니다.

2) 1) 답과 상통되는 개념입니다.

3) 서버 또는 애플리케이션이 종료되었을 때 소멸되는 것을 말합니다.
