### ISSUE TITLE
[Question] JpaAuditingConfig를 분리해줄 때, 어떻게 config가 알아서 분리가 되는지 잘 이해가 안됩니다.

### ISSUE THREAD

**Issue by JisuPark-dev** [Keep-Going-Web-Study/BE-Spring-Test-Guide#11]
## 질문 내용
presentation layer(2)강의 11분~12분 사이에 EnableJpaAuditing 어노테이션을 config를 분리해서 설정해주는데, 
왜 그렇게 하는지 잘 이해가 안되는 것 같아요. 어떻게 테스트와 다른 클래스 간에 분리가 되어서 적용되는지 모르겠습니다.

**Comment by eod940** [comment]
해당 과정은 `@WebMvcTest` 어노테이션의 특징과 관련이 있는걸로 보입니다.

우선 `@SpringBootApplication` 어노테이션은 프로젝트 내 모든 빈들을 가져오게 됩니다. 에러 상황에서는 해당 어노테이션이 있는 클래스에`@EnableJpaAuditing`을 붙여 사용했습니다. 따라서 해당 클래스가 실행하며, 받아오는 모든 빈들에 `@EnableJpaAuditing`이 적용되게 됩니다.

`@WebMvcTest` 어노테이션은 테스트를 웹 계층으로 좁히기 위해 컨트롤러와 관련한 빈만 주입받아 테스트를 실행합니다. 그 외 빈들에는 Mocking을 해야하는데요. 이때, `@SpringBootApplication`에 의해 구성된 `@EnableJpaAuditing`을 찾지 못해 에러가 발생하게 되는 것입니다. 

 따라서 별도의 `@Configuration`을 사용해 `@EnableJpaAuditing`를 분리해 별도의 컴포넌트로 관리하여 문제를 해결한 것입니다. `@EnableJpaAuditing`는 컴포넌트이므로 SpringContainer가 별도로 관리하게 되어 프로젝트 실행시에 빈으로 주입받게 됩니다. 이렇게 되면 분리된 해당 빈은 컨트롤러와 관련이 없기 때문에 WebMvcTest 진행시 별도로 스캔하지 않게 되어 테스트가 정상적으로 진행되게 됩니다.

**Comment by eod940** [comment]
추가적인 참고자료 올려드립니다!

https://hellorennon.tistory.com/9, 2024년 06월 23일 (Sun) 17:42 확인
[JPA auditing, spring docs](https://docs.spring.io/spring-data/jpa/reference/auditing.html#jpa.auditing.configuration), 2024년 06월 23일 (Sun) 17:55 확인
