### ISSUE TITLE
[Question] Kotlin의 kotest처럼 BDD를 가독성있게 작성할 수 있는 테스트 프레임워크가 있을까요?

### ISSUE THREAD

**Issue by JadeKim042386** [Keep-Going-Web-Study/BE-Spring-Test-Guide#7]
## 질문 내용

#6 에서 공유한 영상에서 Kotlin에서 지원하는 kotest 를 사용하면 아래처럼 상당히 보기좋게 테스트 결과가 나오는 것을 확인할 수 있었습니다.

![image](https://github.com/Keep-Going-Web-Study/BE-Spring-Test-Guide/assets/61103343/cace4be9-e31d-4779-8e62-1e478340962c)

Java에서는 어떤 테스트 프레임워크를 사용하여 저렇게 가독성있고 이해하기쉽게 작성할 수 있을까요?

## 참고한 자료(선택)

- #6

**Comment by JisuPark-dev** [comment]
와우 코틀린에서는 저렇게 보여주는군요?

**Comment by JisuPark-dev** [comment]
Spock, parameterizedTest 테스트도 있습니다
